### ISSUE TITLE
Task list component

### ISSUE THREAD

**Issue by brendan-ch** [brendan-ch/clockwise#62]
Acceptance criteria:
- [x] Load/store tasks from database or `AsyncStorage`
- [x] State handling of tasks
- [x] Display lists of tasks (#61)
- [x] Expand task component with name editing and est. pomodoros options
  - [x] Add props/children to enable rendering of task options from task list component
  - [x] Render options conditionally based on timer state and mode
- [x] Create and display "Add task" button
  - [x] Hide this button when timer is running
